/* This file is generated by Cook - DO NOT ALTER */
#define Nav2_Major_rel_def 6
#define Nav2_Minor_rel_def 14
#define Nav2_Build_id_def 2000
#define Nav2_Build_user_def "hfasth"
#define Nav2_Build_host_def "redeemer"
#define Nav2_Build_time_def "Mon May 22 17:35:04 WEDT 2006"
